web: gunicorn kisan_mitra.wsgi:application --log-file - --workers 2 --bind 0.0.0.0:$PORT
# worker: python manage.py process_tasks # For django-background-tasks
# worker: celery -A kisan_mitra worker -l info # For Celery